### PR TITLE
Get Horace-Euphonic-Interface from GitHub artifact

### PR DESCRIPTION
**Pull request by rebeccafair**
As a result of Horace-Euphonic-Interface moving to Github Actions (https://github.com/pace-neutrons/horace-euphonic-interface/pull/27), this requires some changes to get the `mltbx`. Main changes:

* Create `get_artifact_url.py` script to get the `horace_euphonic_interface.mltbx` URL using the Github API
* Update `extract_horace_artifact` script to be more generic so we can use it to extract the `mltbx` too (the URL provided by the Github API is always a .zip currently)
* Specify the Python version in an environment variable (Euphonic requirement has increased from 3.6 -> 3.7). Requires https://github.com/pace-neutrons/PACE-jenkins-shared-library/pull/3 to be merged.

### CODE REVIEW

**Review by mducle — APPROVED** [review]
Looks good :+1:

Considering what Jacob said about `withCredentials` not working with powershell on the new Windows nodes, maybe you can use `curl` (Windows 10 seems to ship with it in `C:\Windows\System32\curl.exe` and it uses the same syntax except you'd need to use `%api_token%`  instead of `${api_token}$` etc.

**Comment by rebeccafair** [comment]
> Considering what Jacob said about `withCredentials` not working with powershell on the new Windows nodes, maybe you can use `curl` (Windows 10 seems to ship with it in `C:\Windows\System32\curl.exe` and it uses the same syntax except you'd need to use `%api_token%` instead of `${api_token}$` etc.

Ah good point, which are the new ones, `icdpacewin`?

**Comment by mducle** [comment]
Yes, `icdpacewin` but we're not using it for `pace-integration` at the moment... it can probably be done in a new PR when the current build server is retired (e.g. when all the bugs have been fixed with the new one ;)

**Comment by rebeccafair** [comment]
> Yes, `icdpacewin` but we're not using it for `pace-integration` at the moment... it can probably be done in a new PR when the current build server is retired (e.g. when all the bugs have been fixed with the new one ;)

I'm happy with that!

**Pull request merged**
